(()=>{"use strict";
const $=id=>document.getElementById(id),P=16,SKEY="easydsp-rec-settings-v1";
const state={ts:1,files:[],aliases:{},colors:{},visible:{},derived:[],scale:"common",zero:false};
const palette=["#2563eb","#dc2626","#059669","#7c3aed","#d97706","#0891b2","#db2777","#4f46e5"];
class RecError extends Error{}
function ascii(u){let s="",c=8192;for(let i=0;i<u.length;i+=c)s+=String.fromCharCode(...u.subarray(i,Math.min(i+c,u.length)));return s}
function channels(u){const h=ascii(u.subarray(0,Math.min(4096,u.length))),re=/m_DATA\d+/g,seen=new Set(),a=[];let m;while((m=re.exec(h)))if(!seen.has(m[0])){seen.add(m[0]);a.push({name:m[0],off:m.index})}return a.sort((x,y)=>+x.name.split("DATA")[1]-+y.name.split("DATA")[1])}
function score(v,start,counts){let p=start,s=0;try{for(const n of counts){for(const i of [...new Set([0,Math.min(1,n-1),Math.min(2,n-1),n-1])]){const o=p+i*P;if(o+16>v.byteLength)return-1;const x=v.getFloat64(o,true),y=v.getFloat64(o+8,true);if(!Number.isFinite(x)||!Number.isFinite(y))return-1;if(Math.abs(x-i)<1e-9)s+=4}p+=n*P}}catch{return-1}return s}
function infer(u,ch){if(!ch.length)throw new RecError("m_DATA# 채널을 찾지 못했습니다.");const v=new DataView(u.buffer,u.byteOffset,u.byteLength),n=ch.length,start=Math.max(...ch.map(x=>x.off))+8,end=Math.min(4096,u.length-4*n),cand=[];for(let o=Math.ceil(start/4)*4;o<end;o+=4){let counts=[],tot=0,ok=true;for(let i=0;i<n;i++){const c=v.getUint32(o+4*i,true);if(c<1||c>1e7){ok=false;break}counts.push(c);tot+=c}if(!ok)continue;const ds=u.length-P*tot;if(ds<=o||ds<0||ds%8)continue;const sc=score(v,ds,counts);if(sc>=10*n)cand.push({o,counts,ds,sc})}if(!cand.length)throw new RecError("지원하지 않는 REC 형식입니다.");cand.sort((a,b)=>b.sc-a.sc||a.o-b.o);return cand[0]}
function parse(buf,name){const u=new Uint8Array(buf);if(u.length<256)throw new RecError("REC 파일이 너무 작습니다.");const ch=channels(u),inf=infer(u,ch),v=new DataView(u.buffer,u.byteOffset,u.byteLength);let p=inf.ds,out=[];ch.forEach((c,k)=>{const n=inf.counts[k],x=new Float64Array(n),y=new Float64Array(n);for(let i=0;i<n;i++){x[i]=v.getFloat64(p+i*P,true);y[i]=v.getFloat64(p+i*P+8,true)}out.push({name:c.name,x,y});p+=n*P});if(p!==u.length)throw new RecError("payload 길이가 일치하지 않습니다.");return{id:crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random(),name,channels:out}}
function load(){try{const s=JSON.parse(localStorage.getItem(SKEY)||"{}");Object.assign(state,{ts:+s.ts||1,aliases:s.aliases||{},colors:s.colors||{},visible:s.visible||{},scale:s.scale||"common",zero:!!s.zero,derived:s.derived||[]})}catch{}}
function save(){localStorage.setItem(SKEY,JSON.stringify({ts:state.ts,aliases:state.aliases,colors:state.colors,visible:state.visible,scale:state.scale,zero:state.zero,derived:state.derived.map(d=>({a:d.a,b:d.b,name:d.name,color:d.color}))}));alert("설정을 저장했습니다.")}
function sid(f,c){return f.id+"::"+c.name}
function alias(n){return state.aliases[n]||n}
function color(n){if(!state.colors[n])state.colors[n]=palette[(+(n.match(/\d+/)||[0])[0])%palette.length];return state.colors[n]}
function base(){let a=[];for(const f of state.files)for(const c of f.channels){const id=sid(f,c);a.push({id,file:f.name,original:c.name,name:alias(c.name),color:color(c.name),x:c.x,y:c.y,visible:state.visible[id]!==false})}return a}
function all(){const b=base(),map=new Map(b.map(x=>[x.id,x])),d=[];for(const q of state.derived){const A=map.get(q.a),B=map.get(q.b);if(!A||!B)continue;const n=Math.min(A.y.length,B.y.length),y=new Float64Array(n),x=new Float64Array(n);for(let i=0;i<n;i++){x[i]=i;y[i]=A.y[i]-B.y[i]}d.push({id:"d:"+q.a+"-"+q.b+"-"+q.name,file:"계산",original:q.name,name:q.name,color:q.color||"#111827",x,y,visible:true,derived:true})}return b.concat(d)}
function fmt(v){if(!Number.isFinite(v))return"-";const a=Math.abs(v);return a>=1e4||a&&a<1e-3?v.toExponential(4):v.toFixed(4).replace(/\.?0+$/,"")}
function time(i){return i*state.ts/1000}
function renderFiles(){$("files").innerHTML=state.files.length?state.files.map(f=>`<div><b>${f.name}</b><div class="hint">${f.channels.length} channels · ${f.channels[0]?.y.length||0} samples</div></div>`).join(""):'<div class="empty">REC 파일을 선택하세요.</div>'}
function renderChannels(){const list=$("channelList"),items=base();if(!items.length){list.innerHTML='<div class="empty">REC 파일을 먼저 열어주세요.</div>';return}list.innerHTML=items.map(s=>`<div class="channel"><input type="checkbox" data-vis="${s.id}" ${s.visible?"checked":""}><div><div class="hint">${s.file} · ${s.original}</div><input type="text" data-alias="${s.original}" value="${alias(s.original)}"></div><input type="color" data-color="${s.original}" value="${color(s.original)}"></div>`).join("");list.querySelectorAll("[data-vis]").forEach(x=>x.onchange=()=>{state.visible[x.dataset.vis]=x.checked;draw();renderStats();renderLegend()});list.querySelectorAll("[data-alias]").forEach(x=>x.onchange=()=>{state.aliases[x.dataset.alias]=x.value.trim()||x.dataset.alias;renderAll()});list.querySelectorAll("[data-color]").forEach(x=>x.oninput=()=>{state.colors[x.dataset.color]=x.value;renderAll()})}
function renderLegend(){const v=all().filter(s=>s.visible);$("legend").innerHTML=v.map(s=>`<span><i style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${s.color};margin-right:5px"></i>${s.name}<small> · ${s.file}</small></span>`).join("")}
function fillDiff(){const a=base();for(const id of["a","b"])$(id).innerHTML=a.map(s=>`<option value="${s.id}">${s.file} · ${s.name}</option>`).join("")}
function stats(s){let min=Infinity,max=-Infinity,mi=0,ma=0,sum=0,sq=0;for(let i=0;i<s.y.length;i++){const y=s.y[i];if(y<min){min=y;mi=i}if(y>max){max=y;ma=i}sum+=y;sq+=y*y}return{min,max,mi,ma,mean:sum/s.y.length,rms:Math.sqrt(sq/s.y.length)}}
function renderStats(){const v=all().filter(s=>s.visible);$("stats").innerHTML=v.length?v.map(s=>{const q=stats(s);return`<tr><td>${s.name}<br><small>${s.file}</small></td><td>${fmt(q.min)}</td><td>${time(q.mi).toFixed(4)} s</td><td>${fmt(q.max)}</td><td>${time(q.ma).toFixed(4)} s</td><td>${fmt(q.mean)}</td><td>${fmt(q.rms)}</td></tr>`}).join(""):'<tr><td colspan="7">표시 데이터가 없습니다.</td></tr>'}
function ranges(series){if(state.scale==="per")return new Map(series.map(s=>{let mn=Math.min(...s.y),mx=Math.max(...s.y);if(state.zero){mn=Math.min(0,mn);mx=Math.max(0,mx)}if(mn===mx){mn-=1;mx+=1}return[s.id,[mn,mx]]}));let mn=Infinity,mx=-Infinity;for(const s of series)for(const y of s.y){if(y<mn)mn=y;if(y>mx)mx=y}if(state.zero){mn=Math.min(0,mn);mx=Math.max(0,mx)}if(!Number.isFinite(mn)){mn=0;mx=1}if(mn===mx){mn--;mx++}return new Map(series.map(s=>[s.id,[mn,mx]]))}
function draw(cursor=null){const cv=$("canvas"),box=cv.getBoundingClientRect(),dpr=devicePixelRatio||1;cv.width=Math.max(1,box.width*dpr);cv.height=Math.max(1,box.height*dpr);const c=cv.getContext("2d");c.scale(dpr,dpr);const W=box.width,H=box.height,L=48,R=12,T=16,B=34,series=all().filter(s=>s.visible);c.clearRect(0,0,W,H);c.strokeStyle="#e2e8f0";c.fillStyle="#64748b";c.font="11px sans-serif";for(let i=0;i<=4;i++){const y=T+(H-T-B)*i/4;c.beginPath();c.moveTo(L,y);c.lineTo(W-R,y);c.stroke()}if(!series.length){c.fillText("표시할 채널을 선택하세요.",L+10,T+30);return}const n=Math.max(...series.map(s=>s.y.length)),rg=ranges(series);for(const s of series){const [mn,mx]=rg.get(s.id);c.strokeStyle=s.color;c.lineWidth=1.7;c.beginPath();for(let i=0;i<s.y.length;i++){const x=L+(W-L-R)*(i/Math.max(1,n-1)),y=T+(H-T-B)*(1-(s.y[i]-mn)/(mx-mn));i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}c.fillStyle="#64748b";c.fillText("0 s",L,H-10);c.fillText((time(n-1)).toFixed(3)+" s",W-R-50,H-10);if(cursor!=null){const i=Math.max(0,Math.min(n-1,cursor));const x=L+(W-L-R)*(i/Math.max(1,n-1));c.strokeStyle="#111827";c.beginPath();c.moveTo(x,T);c.lineTo(x,H-B);c.stroke();$("tip").classList.remove("hidden");$("tip").textContent="Sample "+i+" · "+time(i).toFixed(6)+" s\n"+series.map(s=>s.name+": "+fmt(s.y[Math.min(i,s.y.length-1)])).join("\n")}else $("tip").classList.add("hidden")}
function renderAll(){renderFiles();renderChannels();renderLegend();fillDiff();renderStats();draw()}
async function openFiles(fs){for(const f of fs){try{state.files.push(parse(await f.arrayBuffer(),f.name))}catch(e){alert(f.name+"\n"+e.message)}}renderAll()}
load();
$("ts").value=state.ts;$("scale").value=state.scale;$("zero").checked=state.zero;
$("file").onchange=e=>openFiles(e.target.files);$("ts").onchange=e=>{state.ts=Math.max(.001,+e.target.value||1);renderStats();draw()};$("ts1").onclick=()=>{$("ts").value=state.ts=1;renderStats();draw()};$("ts2").onclick=()=>{$("ts").value=state.ts=2;renderStats();draw()};$("save").onclick=save;$("clear").onclick=()=>{if(confirm("불러온 REC를 모두 제거할까요?")){state.files=[];state.derived=[];renderAll()}};$("scale").onchange=e=>{state.scale=e.target.value;draw()};$("zero").onchange=e=>{state.zero=e.target.checked;draw()};$("addDiff").onclick=()=>{const a=$("a").value,b=$("b").value;if(!a||!b||a===b)return alert("서로 다른 두 데이터를 선택하세요.");state.derived.push({a,b,name:$("diffName").value.trim()||"A-B",color:"#111827"});renderAll()};
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));t.classList.add("active");$(t.dataset.tab).classList.add("active");if(t.dataset.tab==="graph")setTimeout(()=>draw(),20)});
$("canvas").addEventListener("pointerdown",e=>{const s=all().filter(x=>x.visible);if(!s.length)return;const r=e.currentTarget.getBoundingClientRect(),L=48,R=12,n=Math.max(...s.map(x=>x.y.length)),f=Math.max(0,Math.min(1,(e.clientX-r.left-L)/(r.width-L-R))),i=Math.round(f*(n-1));draw(i)});
window.addEventListener("resize",()=>draw());if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js").catch(()=>{});
renderAll();
})();